#!/bin/bash
echo ""
echo "====================================================================================="
echo "Menu Board > Manage SSL Certificate"
echo "/-------------------------/"
echo "- Manage SSL Certificate"
echo "/-----------------------------------------------------------------------------------/"
echo 
PS3='Input number you choose (1-2) [0=Exit]: '
options=("Install Free SSL Let's Encrypt For Domain" "Install Paid SSL For Domain")
select opt in "${options[@]}"
do
    case $opt in
        "Install Free SSL Let's Encrypt For Domain")
            '/etc/quicklemp/menu/ssl/ssl_let'
            ;;
        "Install Paid SSL For Domain")
            '/etc/quicklemp/menu/ssl/ssl_traphi'
            ;;
        *) tino;;
    esac
done

